name: Rust build and test

on:
  push:
    branches: "**"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Check format
        run: cargo fmt --all -- --check
